use crate::Embed;
use crate::embeddings::{EmbeddingModel, EmbeddingsBuilder};

/// A provider client with embedding capabilities.
/// Clone is required for conversions between client types.
pub trait EmbeddingsClient {
    /// The type of EmbeddingModel used by the Client
    type EmbeddingModel: EmbeddingModel;

    /// Create an embedding model with the given model.
    ///
    /// # Example
    /// ```no_run
    /// use rig_core::prelude::*;
    /// use rig_core::providers::openai::{Client, self};
    ///
    /// # fn run() -> Result<(), Box<dyn std::error::Error>> {
    /// // Initialize the OpenAI client
    /// let openai = Client::new("your-open-ai-api-key")?;
    ///
    /// let embedding_model = openai.embedding_model("text-embedding-3-large");
    /// # Ok(())
    /// # }
    /// ```
    fn embedding_model(&self, model: impl Into<String>) -> Self::EmbeddingModel;

    /// Create an embedding model with the given model identifier string and the number of dimensions in the embedding generated by the model.
    /// Use this when the provider supports a model whose dimensionality is not
    /// known by Rig.
    ///
    /// # Example with OpenAI
    /// ```no_run
    /// use rig_core::prelude::*;
    /// use rig_core::providers::openai::{Client, self};
    ///
    /// # fn run() -> Result<(), Box<dyn std::error::Error>> {
    /// // Initialize the OpenAI client
    /// let openai = Client::new("your-open-ai-api-key")?;
    ///
    /// let embedding_model = openai.embedding_model_with_ndims("model-unknown-to-rig", 3072);
    /// # Ok(())
    /// # }
    /// ```
    fn embedding_model_with_ndims(
        &self,
        model: impl Into<String>,
        ndims: usize,
    ) -> Self::EmbeddingModel;

    /// Create an embedding builder with the given embedding model.
    ///
    /// # Example with OpenAI
    /// ```no_run
    /// use rig_core::prelude::*;
    /// use rig_core::providers::openai::{Client, self};
    ///
    /// # async fn run() -> Result<(), Box<dyn std::error::Error>> {
    /// // Initialize the OpenAI client
    /// let openai = Client::new("your-open-ai-api-key")?;
    ///
    /// let embeddings = openai.embeddings("text-embedding-3-large")
    ///     .documents(vec!["Hello, world!", "Goodbye, world!"])?
    ///     .build()
    ///     .await?;
    /// # Ok(())
    /// # }
    /// ```
    fn embeddings<D: Embed>(
        &self,
        model: impl Into<String>,
    ) -> EmbeddingsBuilder<Self::EmbeddingModel, D> {
        EmbeddingsBuilder::new(self.embedding_model(model))
    }

    /// Create an embedding builder with the given name and the number of dimensions in the embedding generated by the model.
    ///
    /// # Example with OpenAI
    /// ```no_run
    /// use rig_core::prelude::*;
    /// use rig_core::providers::openai::{Client, self};
    ///
    /// # async fn run() -> Result<(), Box<dyn std::error::Error>> {
    /// // Initialize the OpenAI client
    /// let openai = Client::new("your-open-ai-api-key")?;
    ///
    /// let embeddings = openai.embeddings_with_ndims("text-embedding-3-large", 3072)
    ///     .documents(vec!["Hello, world!", "Goodbye, world!"])?
    ///     .build()
    ///     .await?;
    /// # Ok(())
    /// # }
    /// ```
    fn embeddings_with_ndims<D: Embed>(
        &self,
        model: &str,
        ndims: usize,
    ) -> EmbeddingsBuilder<Self::EmbeddingModel, D> {
        EmbeddingsBuilder::new(self.embedding_model_with_ndims(model, ndims))
    }
}

#[cfg(test)]
mod tests {
    use crate::client::EmbeddingsClient;
    use crate::providers::openai::CompletionsClient;
    use crate::test_utils::RecordingHttpClient;

    const RESPONSE_BODY: &str = r#"{
        "object": "list",
        "model": "text-embedding-3-small",
        "usage": { "prompt_tokens": 4, "total_tokens": 4 },
        "data": [
            { "object": "embedding", "index": 0, "embedding": [0.1, 0.2] },
            { "object": "embedding", "index": 1, "embedding": [0.3, 0.4] }
        ]
    }"#;

    #[tokio::test]
    async fn embeddings_builds_a_batch_builder_around_the_named_model() {
        let http_backend = RecordingHttpClient::new(RESPONSE_BODY);
        let client = CompletionsClient::builder()
            .api_key("test-key")
            .http_client(http_backend.clone())
            .build()
            .expect("build client");

        let mut embeddings = client
            .embeddings::<String>("text-embedding-3-small")
            .documents(["hello".to_string(), "world".to_string()])
            .expect("documents should embed")
            .build()
            .await
            .expect("embedding request should succeed");

        // `build` merges per-document embeddings through a HashMap, so the
        // result order is unspecified.
        embeddings.sort_by_key(|(document, _)| document.clone());

        assert_eq!(embeddings.len(), 2);
        assert_eq!(embeddings[0].0, "hello");
        assert_eq!(embeddings[1].0, "world");

        let requests = http_backend.requests();
        assert_eq!(requests.len(), 1);
        let body: serde_json::Value =
            serde_json::from_slice(&requests[0].body).expect("request body should be JSON");
        assert_eq!(
            body["input"],
            serde_json::json!(["hello", "world"]),
            "both documents should be batched into one request"
        );
        assert!(
            body.get("dimensions").is_none(),
            "no dimensions should be requested without ndims"
        );
    }

    #[tokio::test]
    async fn embeddings_with_ndims_passes_dimensions_to_the_model() {
        let http_backend = RecordingHttpClient::new(RESPONSE_BODY);
        let client = CompletionsClient::builder()
            .api_key("test-key")
            .http_client(http_backend.clone())
            .build()
            .expect("build client");

        let mut embeddings = client
            .embeddings_with_ndims::<String>("text-embedding-3-small", 1_536)
            .documents(["hello".to_string(), "world".to_string()])
            .expect("documents should embed")
            .build()
            .await
            .expect("embedding request should succeed");

        embeddings.sort_by_key(|(document, _)| document.clone());
        assert_eq!(embeddings.len(), 2);

        let requests = http_backend.requests();
        assert_eq!(requests.len(), 1);
        let body: serde_json::Value =
            serde_json::from_slice(&requests[0].body).expect("request body should be JSON");
        assert_eq!(body["dimensions"], serde_json::json!(1_536));
    }
}
