use serde::Serialize;
use std::collections::HashMap;

use crate::{OneOrMany, embeddings::Embedding};

use super::{IndexStrategy, in_memory_store::InMemoryVectorStore};

/// Builder for creating an [`InMemoryVectorStore`] with custom configuration.
pub struct InMemoryVectorStoreBuilder<D>
where
    D: Serialize,
{
    /// Embeddings of the documents.
    embeddings: HashMap<String, (D, OneOrMany<Embedding>)>,

    /// Index strategy for the vector store.
    index_strategy: IndexStrategy,
}

impl<D> Default for InMemoryVectorStoreBuilder<D>
where
    D: Serialize + Eq,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<D> InMemoryVectorStoreBuilder<D>
where
    D: Serialize + Eq,
{
    /// Create a new builder with default settings.
    ///
    /// The default index strategy is [`IndexStrategy::BruteForce`].
    pub fn new() -> Self {
        Self {
            embeddings: HashMap::new(),
            index_strategy: IndexStrategy::default(),
        }
    }

    /// Set the index strategy for the vector store.
    ///
    /// # Examples
    ///
    /// ```
    /// use rig_core::vector_store::{builder::InMemoryVectorStoreBuilder, IndexStrategy};
    ///
    /// let store = InMemoryVectorStoreBuilder::<String>::new()
    ///     .index_strategy(IndexStrategy::LSH {
    ///         num_tables: 5,
    ///         num_hyperplanes: 10,
    ///     })
    ///     .build();
    /// ```
    pub fn index_strategy(mut self, index_strategy: IndexStrategy) -> Self {
        self.index_strategy = index_strategy;
        self
    }

    /// Add documents with auto-generated IDs.
    /// IDs will have the form `"doc{n}"` where `n` is the index.
    pub fn documents(
        mut self,
        documents: impl IntoIterator<Item = (D, OneOrMany<Embedding>)>,
    ) -> Self {
        let current_index = self.embeddings.len();
        documents
            .into_iter()
            .enumerate()
            .for_each(|(i, (doc, embeddings))| {
                self.embeddings
                    .insert(format!("doc{}", i + current_index), (doc, embeddings));
            });
        self
    }

    /// Add documents with explicit IDs.
    pub fn documents_with_ids(
        mut self,
        documents: impl IntoIterator<Item = (impl ToString, D, OneOrMany<Embedding>)>,
    ) -> Self {
        documents.into_iter().for_each(|(id, doc, embeddings)| {
            self.embeddings.insert(id.to_string(), (doc, embeddings));
        });
        self
    }

    /// Add documents with IDs generated by a function.
    pub fn documents_with_id_f(
        mut self,
        documents: impl IntoIterator<Item = (D, OneOrMany<Embedding>)>,
        f: fn(&D) -> String,
    ) -> Self {
        documents.into_iter().for_each(|(doc, embeddings)| {
            let id = f(&doc);
            self.embeddings.insert(id, (doc, embeddings));
        });
        self
    }

    /// Build the [`InMemoryVectorStore`] with the configured settings.
    pub fn build(self) -> InMemoryVectorStore<D> {
        InMemoryVectorStore::from_builder(self.embeddings, self.index_strategy)
    }
}

#[cfg(test)]
mod tests {
    use serde::Serialize;

    use crate::{OneOrMany, embeddings::embedding::Embedding};

    use super::InMemoryVectorStoreBuilder;

    #[derive(Clone, Debug, Serialize, PartialEq, Eq)]
    struct Doc {
        name: String,
    }

    fn doc(name: &str, vec: Vec<f64>) -> (Doc, OneOrMany<Embedding>) {
        (
            Doc {
                name: name.to_string(),
            },
            OneOrMany::one(Embedding {
                document: name.to_string(),
                vec,
            }),
        )
    }

    fn ids_in_insertion_order(mut pairs: Vec<(String, Doc)>) -> Vec<String> {
        pairs.sort_by(|(a, _), (b, _)| a.cmp(b));
        pairs.into_iter().map(|(id, _)| id).collect()
    }

    #[test]
    fn default_builds_an_empty_brute_force_store() {
        let store = InMemoryVectorStoreBuilder::<String>::default().build();

        assert!(store.is_empty());
        assert_eq!(store.len(), 0);
    }

    #[test]
    fn documents_with_id_f_uses_supplied_function() {
        fn upper_name(doc: &Doc) -> String {
            doc.name.to_uppercase()
        }

        let store = InMemoryVectorStoreBuilder::new()
            .documents_with_id_f(
                vec![doc("abc", vec![0.1, 0.2, 0.3]), doc("de", vec![0.3, 0.2, 0.1])],
                upper_name,
            )
            .build();

        let pairs: Vec<(String, Doc)> = store
            .iter()
            .map(|(id, (doc, _))| (id.clone(), doc.clone()))
            .collect();

        assert_eq!(
            ids_in_insertion_order(pairs),
            vec!["ABC".to_string(), "DE".to_string()]
        );
        assert_eq!(store.len(), 2);
    }

    #[test]
    fn documents_continue_auto_id_numbering_across_calls() {
        let store = InMemoryVectorStoreBuilder::new()
            .documents(vec![doc("first", vec![0.1, 0.2, 0.3])])
            .documents(vec![doc("second", vec![0.3, 0.2, 0.1])])
            .build();

        let pairs: Vec<(String, Doc)> = store
            .iter()
            .map(|(id, (doc, _))| (id.clone(), doc.clone()))
            .collect();

        assert_eq!(
            ids_in_insertion_order(pairs),
            vec!["doc0".to_string(), "doc1".to_string()]
        );
    }

    #[test]
    fn documents_with_ids_keeps_explicit_ids() {
        let (doc, embeddings) = doc("named", vec![0.1, 0.2, 0.3]);
        let store = InMemoryVectorStoreBuilder::new()
            .documents_with_ids(vec![("custom-id", doc, embeddings)])
            .build();

        let pairs: Vec<(String, Doc)> = store
            .iter()
            .map(|(id, (doc, _))| (id.clone(), doc.clone()))
            .collect();

        assert_eq!(
            pairs,
            vec![(
                "custom-id".to_string(),
                Doc {
                    name: "named".to_string()
                }
            )]
        );
    }
}
